
name: Scala CI

on:
  pull_request:
    types: [opened, closed,reopened,edited] 
    branches: [ "main" ]
  push:
    branches: ["main"] 
    
jobs:
  build_sbt:
    name: Build Project
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        scala: [2.13.12,3.3.0]
        java: [temurin@17]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
      with:
       fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main
      with:
        jvm: temurin:17
        apps: sbt 
    - run: sbt compile
  build_sbtn:
    name: Build Project
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        scala: [2.13.12,3.3.0]
        java: [temurin@17]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
      with:
       fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: VirtusLab/scala-cli-setup@main
      with:
        jvm: temurin:17
        apps: sbtn  
    - run: sbtn compile               
